[build]
builder = "RAILPACK"
buildCommand = "APP_ENV=production vp build"
preDeployCommand = "APP_ENV=production vp run db:push"

[deploy]
runtime = "V2"
numReplicas = 1
startCommand = "vp run start"
healthcheckPath = "/"
sleepApplication = true
useLegacyStacker = false
ipv6EgressEnabled = false
restartPolicyType = "ALWAYS"
healthcheckTimeout = 300
