import type { MatchDetails } from '@/components/match/card'

export const consumerMatches: MatchDetails[] = [
	{
		id: 'consumer-1',
		name: 'Sarah Chen',
		role: 'agent',
		location: 'Austin, TX',
		zipCodes: ['78701'],
		fitScore: 96,
		status: 'new',
		date: 'Just now',
		experience: '12 years',
		agency: 'Horizon Realty Group',
		avatar: 'https://i.pravatar.cc/150?u=sarah-chen',
		specialties: ['First-time buyers', 'Luxury homes', 'Calm negotiation'],
		about:
			'Known for patient guidance and transparent communication. Strong fit for clients who want a steady, low-pressure process.',
		scores: {
			'Working Style': 4.9,
			Communication: 4.7,
			Transparency: 4.8,
			Fit: 4.9,
		},
		isTopMatch: true,
	},
	{
		id: 'consumer-2',
		name: 'Marcus Johnson',
		role: 'agent',
		location: 'Austin, TX',
		zipCodes: ['78701'],
		fitScore: 90,
		status: 'new',
		date: 'Just now',
		experience: '8 years',
		agency: 'Urban Nest Properties',
		avatar: 'https://i.pravatar.cc/150?u=marcus-johnson',
		specialties: ['Fast timelines', 'Urban properties', 'Relocation'],
		about:
			'Efficient, data-driven agent who respects your time and keeps decisions moving without extra drama.',
		scores: {
			'Working Style': 4.6,
			Communication: 4.4,
			Transparency: 4.5,
			Fit: 4.4,
		},
		isTopMatch: false,
	},
	{
		id: 'consumer-3',
		name: 'Elena Rodriguez',
		role: 'agent',
		location: 'Austin, TX',
		zipCodes: ['78701'],
		fitScore: 88,
		status: 'new',
		date: 'Just now',
		experience: '6 years',
		agency: 'Coastal Living Realty',
		avatar: 'https://i.pravatar.cc/150?u=elena-rodriguez',
		specialties: ['Waterfront', 'Condos', 'Vacation Homes'],
		about:
			'Elena brings a fresh perspective to real estate. Her background in interior design helps clients envision the potential in every property she shows.',
		scores: {
			'Working Style': 4.5,
			Communication: 4.6,
			Transparency: 4.4,
			Fit: 4.5,
		},
		isTopMatch: false,
	},
]
