/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as BetaRouteImport } from './routes/beta'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConsumerIndexRouteImport } from './routes/consumer/index'
import { Route as AgentIndexRouteImport } from './routes/agent/index'
import { Route as ConsumerDashboardRouteImport } from './routes/consumer/dashboard'
import { Route as ApiAgentMatchesRouteImport } from './routes/api/agent-matches'
import { Route as AgentDashboardRouteImport } from './routes/agent/dashboard'
import { Route as ConsumerSignupIndexRouteImport } from './routes/consumer/signup/index'
import { Route as ConsumerDashboardIndexRouteImport } from './routes/consumer/dashboard/index'
import { Route as AgentSignupIndexRouteImport } from './routes/agent/signup/index'
import { Route as AgentDashboardIndexRouteImport } from './routes/agent/dashboard/index'
import { Route as ConsumerDashboardSearchPreferencesRouteImport } from './routes/consumer/dashboard/search-preferences'
import { Route as ConsumerDashboardPracticeNegotiatingRouteImport } from './routes/consumer/dashboard/practice-negotiating'
import { Route as ConsumerDashboardMatchesRouteImport } from './routes/consumer/dashboard/matches'
import { Route as ConsumerDashboardIntroductionsRouteImport } from './routes/consumer/dashboard/introductions'
import { Route as ApiIngestSplatRouteImport } from './routes/api/ingest/$'
import { Route as ApiBetaAuthRouteImport } from './routes/api/beta/auth'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AgentDashboardValuePropositionRouteImport } from './routes/agent/dashboard/value-proposition'
import { Route as AgentDashboardSubscribeRouteImport } from './routes/agent/dashboard/subscribe'
import { Route as AgentDashboardProfileRouteImport } from './routes/agent/dashboard/profile'
import { Route as AgentDashboardPeacePactRouteImport } from './routes/agent/dashboard/peace-pact'
import { Route as AgentDashboardIntroductionsRouteImport } from './routes/agent/dashboard/introductions'
import { Route as AgentDashboardComplianceRouteImport } from './routes/agent/dashboard/compliance'
import { Route as ApiIngestStaticSplatRouteImport } from './routes/api/ingest/static/$'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const BetaRoute = BetaRouteImport.update({
  id: '/beta',
  path: '/beta',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsumerIndexRoute = ConsumerIndexRouteImport.update({
  id: '/consumer/',
  path: '/consumer/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentIndexRoute = AgentIndexRouteImport.update({
  id: '/agent/',
  path: '/agent/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsumerDashboardRoute = ConsumerDashboardRouteImport.update({
  id: '/consumer/dashboard',
  path: '/consumer/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentMatchesRoute = ApiAgentMatchesRouteImport.update({
  id: '/api/agent-matches',
  path: '/api/agent-matches',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentDashboardRoute = AgentDashboardRouteImport.update({
  id: '/agent/dashboard',
  path: '/agent/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsumerSignupIndexRoute = ConsumerSignupIndexRouteImport.update({
  id: '/consumer/signup/',
  path: '/consumer/signup/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsumerDashboardIndexRoute = ConsumerDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ConsumerDashboardRoute,
} as any)
const AgentSignupIndexRoute = AgentSignupIndexRouteImport.update({
  id: '/agent/signup/',
  path: '/agent/signup/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentDashboardIndexRoute = AgentDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AgentDashboardRoute,
} as any)
const ConsumerDashboardSearchPreferencesRoute =
  ConsumerDashboardSearchPreferencesRouteImport.update({
    id: '/search-preferences',
    path: '/search-preferences',
    getParentRoute: () => ConsumerDashboardRoute,
  } as any)
const ConsumerDashboardPracticeNegotiatingRoute =
  ConsumerDashboardPracticeNegotiatingRouteImport.update({
    id: '/practice-negotiating',
    path: '/practice-negotiating',
    getParentRoute: () => ConsumerDashboardRoute,
  } as any)
const ConsumerDashboardMatchesRoute =
  ConsumerDashboardMatchesRouteImport.update({
    id: '/matches',
    path: '/matches',
    getParentRoute: () => ConsumerDashboardRoute,
  } as any)
const ConsumerDashboardIntroductionsRoute =
  ConsumerDashboardIntroductionsRouteImport.update({
    id: '/introductions',
    path: '/introductions',
    getParentRoute: () => ConsumerDashboardRoute,
  } as any)
const ApiIngestSplatRoute = ApiIngestSplatRouteImport.update({
  id: '/api/ingest/$',
  path: '/api/ingest/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBetaAuthRoute = ApiBetaAuthRouteImport.update({
  id: '/api/beta/auth',
  path: '/api/beta/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentDashboardValuePropositionRoute =
  AgentDashboardValuePropositionRouteImport.update({
    id: '/value-proposition',
    path: '/value-proposition',
    getParentRoute: () => AgentDashboardRoute,
  } as any)
const AgentDashboardSubscribeRoute = AgentDashboardSubscribeRouteImport.update({
  id: '/subscribe',
  path: '/subscribe',
  getParentRoute: () => AgentDashboardRoute,
} as any)
const AgentDashboardProfileRoute = AgentDashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AgentDashboardRoute,
} as any)
const AgentDashboardPeacePactRoute = AgentDashboardPeacePactRouteImport.update({
  id: '/peace-pact',
  path: '/peace-pact',
  getParentRoute: () => AgentDashboardRoute,
} as any)
const AgentDashboardIntroductionsRoute =
  AgentDashboardIntroductionsRouteImport.update({
    id: '/introductions',
    path: '/introductions',
    getParentRoute: () => AgentDashboardRoute,
  } as any)
const AgentDashboardComplianceRoute =
  AgentDashboardComplianceRouteImport.update({
    id: '/compliance',
    path: '/compliance',
    getParentRoute: () => AgentDashboardRoute,
  } as any)
const ApiIngestStaticSplatRoute = ApiIngestStaticSplatRouteImport.update({
  id: '/api/ingest/static/$',
  path: '/api/ingest/static/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/beta': typeof BetaRoute
  '/login': typeof LoginRoute
  '/agent/dashboard': typeof AgentDashboardRouteWithChildren
  '/api/agent-matches': typeof ApiAgentMatchesRoute
  '/consumer/dashboard': typeof ConsumerDashboardRouteWithChildren
  '/agent/': typeof AgentIndexRoute
  '/consumer/': typeof ConsumerIndexRoute
  '/agent/dashboard/compliance': typeof AgentDashboardComplianceRoute
  '/agent/dashboard/introductions': typeof AgentDashboardIntroductionsRoute
  '/agent/dashboard/peace-pact': typeof AgentDashboardPeacePactRoute
  '/agent/dashboard/profile': typeof AgentDashboardProfileRoute
  '/agent/dashboard/subscribe': typeof AgentDashboardSubscribeRoute
  '/agent/dashboard/value-proposition': typeof AgentDashboardValuePropositionRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/beta/auth': typeof ApiBetaAuthRoute
  '/api/ingest/$': typeof ApiIngestSplatRoute
  '/consumer/dashboard/introductions': typeof ConsumerDashboardIntroductionsRoute
  '/consumer/dashboard/matches': typeof ConsumerDashboardMatchesRoute
  '/consumer/dashboard/practice-negotiating': typeof ConsumerDashboardPracticeNegotiatingRoute
  '/consumer/dashboard/search-preferences': typeof ConsumerDashboardSearchPreferencesRoute
  '/agent/dashboard/': typeof AgentDashboardIndexRoute
  '/agent/signup/': typeof AgentSignupIndexRoute
  '/consumer/dashboard/': typeof ConsumerDashboardIndexRoute
  '/consumer/signup/': typeof ConsumerSignupIndexRoute
  '/api/ingest/static/$': typeof ApiIngestStaticSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/beta': typeof BetaRoute
  '/login': typeof LoginRoute
  '/api/agent-matches': typeof ApiAgentMatchesRoute
  '/agent': typeof AgentIndexRoute
  '/consumer': typeof ConsumerIndexRoute
  '/agent/dashboard/compliance': typeof AgentDashboardComplianceRoute
  '/agent/dashboard/introductions': typeof AgentDashboardIntroductionsRoute
  '/agent/dashboard/peace-pact': typeof AgentDashboardPeacePactRoute
  '/agent/dashboard/profile': typeof AgentDashboardProfileRoute
  '/agent/dashboard/subscribe': typeof AgentDashboardSubscribeRoute
  '/agent/dashboard/value-proposition': typeof AgentDashboardValuePropositionRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/beta/auth': typeof ApiBetaAuthRoute
  '/api/ingest/$': typeof ApiIngestSplatRoute
  '/consumer/dashboard/introductions': typeof ConsumerDashboardIntroductionsRoute
  '/consumer/dashboard/matches': typeof ConsumerDashboardMatchesRoute
  '/consumer/dashboard/practice-negotiating': typeof ConsumerDashboardPracticeNegotiatingRoute
  '/consumer/dashboard/search-preferences': typeof ConsumerDashboardSearchPreferencesRoute
  '/agent/dashboard': typeof AgentDashboardIndexRoute
  '/agent/signup': typeof AgentSignupIndexRoute
  '/consumer/dashboard': typeof ConsumerDashboardIndexRoute
  '/consumer/signup': typeof ConsumerSignupIndexRoute
  '/api/ingest/static/$': typeof ApiIngestStaticSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/beta': typeof BetaRoute
  '/login': typeof LoginRoute
  '/agent/dashboard': typeof AgentDashboardRouteWithChildren
  '/api/agent-matches': typeof ApiAgentMatchesRoute
  '/consumer/dashboard': typeof ConsumerDashboardRouteWithChildren
  '/agent/': typeof AgentIndexRoute
  '/consumer/': typeof ConsumerIndexRoute
  '/agent/dashboard/compliance': typeof AgentDashboardComplianceRoute
  '/agent/dashboard/introductions': typeof AgentDashboardIntroductionsRoute
  '/agent/dashboard/peace-pact': typeof AgentDashboardPeacePactRoute
  '/agent/dashboard/profile': typeof AgentDashboardProfileRoute
  '/agent/dashboard/subscribe': typeof AgentDashboardSubscribeRoute
  '/agent/dashboard/value-proposition': typeof AgentDashboardValuePropositionRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/beta/auth': typeof ApiBetaAuthRoute
  '/api/ingest/$': typeof ApiIngestSplatRoute
  '/consumer/dashboard/introductions': typeof ConsumerDashboardIntroductionsRoute
  '/consumer/dashboard/matches': typeof ConsumerDashboardMatchesRoute
  '/consumer/dashboard/practice-negotiating': typeof ConsumerDashboardPracticeNegotiatingRoute
  '/consumer/dashboard/search-preferences': typeof ConsumerDashboardSearchPreferencesRoute
  '/agent/dashboard/': typeof AgentDashboardIndexRoute
  '/agent/signup/': typeof AgentSignupIndexRoute
  '/consumer/dashboard/': typeof ConsumerDashboardIndexRoute
  '/consumer/signup/': typeof ConsumerSignupIndexRoute
  '/api/ingest/static/$': typeof ApiIngestStaticSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/beta'
    | '/login'
    | '/agent/dashboard'
    | '/api/agent-matches'
    | '/consumer/dashboard'
    | '/agent/'
    | '/consumer/'
    | '/agent/dashboard/compliance'
    | '/agent/dashboard/introductions'
    | '/agent/dashboard/peace-pact'
    | '/agent/dashboard/profile'
    | '/agent/dashboard/subscribe'
    | '/agent/dashboard/value-proposition'
    | '/api/auth/$'
    | '/api/beta/auth'
    | '/api/ingest/$'
    | '/consumer/dashboard/introductions'
    | '/consumer/dashboard/matches'
    | '/consumer/dashboard/practice-negotiating'
    | '/consumer/dashboard/search-preferences'
    | '/agent/dashboard/'
    | '/agent/signup/'
    | '/consumer/dashboard/'
    | '/consumer/signup/'
    | '/api/ingest/static/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/beta'
    | '/login'
    | '/api/agent-matches'
    | '/agent'
    | '/consumer'
    | '/agent/dashboard/compliance'
    | '/agent/dashboard/introductions'
    | '/agent/dashboard/peace-pact'
    | '/agent/dashboard/profile'
    | '/agent/dashboard/subscribe'
    | '/agent/dashboard/value-proposition'
    | '/api/auth/$'
    | '/api/beta/auth'
    | '/api/ingest/$'
    | '/consumer/dashboard/introductions'
    | '/consumer/dashboard/matches'
    | '/consumer/dashboard/practice-negotiating'
    | '/consumer/dashboard/search-preferences'
    | '/agent/dashboard'
    | '/agent/signup'
    | '/consumer/dashboard'
    | '/consumer/signup'
    | '/api/ingest/static/$'
  id:
    | '__root__'
    | '/'
    | '/beta'
    | '/login'
    | '/agent/dashboard'
    | '/api/agent-matches'
    | '/consumer/dashboard'
    | '/agent/'
    | '/consumer/'
    | '/agent/dashboard/compliance'
    | '/agent/dashboard/introductions'
    | '/agent/dashboard/peace-pact'
    | '/agent/dashboard/profile'
    | '/agent/dashboard/subscribe'
    | '/agent/dashboard/value-proposition'
    | '/api/auth/$'
    | '/api/beta/auth'
    | '/api/ingest/$'
    | '/consumer/dashboard/introductions'
    | '/consumer/dashboard/matches'
    | '/consumer/dashboard/practice-negotiating'
    | '/consumer/dashboard/search-preferences'
    | '/agent/dashboard/'
    | '/agent/signup/'
    | '/consumer/dashboard/'
    | '/consumer/signup/'
    | '/api/ingest/static/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BetaRoute: typeof BetaRoute
  LoginRoute: typeof LoginRoute
  AgentDashboardRoute: typeof AgentDashboardRouteWithChildren
  ApiAgentMatchesRoute: typeof ApiAgentMatchesRoute
  ConsumerDashboardRoute: typeof ConsumerDashboardRouteWithChildren
  AgentIndexRoute: typeof AgentIndexRoute
  ConsumerIndexRoute: typeof ConsumerIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiBetaAuthRoute: typeof ApiBetaAuthRoute
  ApiIngestSplatRoute: typeof ApiIngestSplatRoute
  AgentSignupIndexRoute: typeof AgentSignupIndexRoute
  ConsumerSignupIndexRoute: typeof ConsumerSignupIndexRoute
  ApiIngestStaticSplatRoute: typeof ApiIngestStaticSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beta': {
      id: '/beta'
      path: '/beta'
      fullPath: '/beta'
      preLoaderRoute: typeof BetaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consumer/': {
      id: '/consumer/'
      path: '/consumer'
      fullPath: '/consumer/'
      preLoaderRoute: typeof ConsumerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/': {
      id: '/agent/'
      path: '/agent'
      fullPath: '/agent/'
      preLoaderRoute: typeof AgentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consumer/dashboard': {
      id: '/consumer/dashboard'
      path: '/consumer/dashboard'
      fullPath: '/consumer/dashboard'
      preLoaderRoute: typeof ConsumerDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent-matches': {
      id: '/api/agent-matches'
      path: '/api/agent-matches'
      fullPath: '/api/agent-matches'
      preLoaderRoute: typeof ApiAgentMatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/dashboard': {
      id: '/agent/dashboard'
      path: '/agent/dashboard'
      fullPath: '/agent/dashboard'
      preLoaderRoute: typeof AgentDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consumer/signup/': {
      id: '/consumer/signup/'
      path: '/consumer/signup'
      fullPath: '/consumer/signup/'
      preLoaderRoute: typeof ConsumerSignupIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consumer/dashboard/': {
      id: '/consumer/dashboard/'
      path: '/'
      fullPath: '/consumer/dashboard/'
      preLoaderRoute: typeof ConsumerDashboardIndexRouteImport
      parentRoute: typeof ConsumerDashboardRoute
    }
    '/agent/signup/': {
      id: '/agent/signup/'
      path: '/agent/signup'
      fullPath: '/agent/signup/'
      preLoaderRoute: typeof AgentSignupIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/dashboard/': {
      id: '/agent/dashboard/'
      path: '/'
      fullPath: '/agent/dashboard/'
      preLoaderRoute: typeof AgentDashboardIndexRouteImport
      parentRoute: typeof AgentDashboardRoute
    }
    '/consumer/dashboard/search-preferences': {
      id: '/consumer/dashboard/search-preferences'
      path: '/search-preferences'
      fullPath: '/consumer/dashboard/search-preferences'
      preLoaderRoute: typeof ConsumerDashboardSearchPreferencesRouteImport
      parentRoute: typeof ConsumerDashboardRoute
    }
    '/consumer/dashboard/practice-negotiating': {
      id: '/consumer/dashboard/practice-negotiating'
      path: '/practice-negotiating'
      fullPath: '/consumer/dashboard/practice-negotiating'
      preLoaderRoute: typeof ConsumerDashboardPracticeNegotiatingRouteImport
      parentRoute: typeof ConsumerDashboardRoute
    }
    '/consumer/dashboard/matches': {
      id: '/consumer/dashboard/matches'
      path: '/matches'
      fullPath: '/consumer/dashboard/matches'
      preLoaderRoute: typeof ConsumerDashboardMatchesRouteImport
      parentRoute: typeof ConsumerDashboardRoute
    }
    '/consumer/dashboard/introductions': {
      id: '/consumer/dashboard/introductions'
      path: '/introductions'
      fullPath: '/consumer/dashboard/introductions'
      preLoaderRoute: typeof ConsumerDashboardIntroductionsRouteImport
      parentRoute: typeof ConsumerDashboardRoute
    }
    '/api/ingest/$': {
      id: '/api/ingest/$'
      path: '/api/ingest/$'
      fullPath: '/api/ingest/$'
      preLoaderRoute: typeof ApiIngestSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/beta/auth': {
      id: '/api/beta/auth'
      path: '/api/beta/auth'
      fullPath: '/api/beta/auth'
      preLoaderRoute: typeof ApiBetaAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/dashboard/value-proposition': {
      id: '/agent/dashboard/value-proposition'
      path: '/value-proposition'
      fullPath: '/agent/dashboard/value-proposition'
      preLoaderRoute: typeof AgentDashboardValuePropositionRouteImport
      parentRoute: typeof AgentDashboardRoute
    }
    '/agent/dashboard/subscribe': {
      id: '/agent/dashboard/subscribe'
      path: '/subscribe'
      fullPath: '/agent/dashboard/subscribe'
      preLoaderRoute: typeof AgentDashboardSubscribeRouteImport
      parentRoute: typeof AgentDashboardRoute
    }
    '/agent/dashboard/profile': {
      id: '/agent/dashboard/profile'
      path: '/profile'
      fullPath: '/agent/dashboard/profile'
      preLoaderRoute: typeof AgentDashboardProfileRouteImport
      parentRoute: typeof AgentDashboardRoute
    }
    '/agent/dashboard/peace-pact': {
      id: '/agent/dashboard/peace-pact'
      path: '/peace-pact'
      fullPath: '/agent/dashboard/peace-pact'
      preLoaderRoute: typeof AgentDashboardPeacePactRouteImport
      parentRoute: typeof AgentDashboardRoute
    }
    '/agent/dashboard/introductions': {
      id: '/agent/dashboard/introductions'
      path: '/introductions'
      fullPath: '/agent/dashboard/introductions'
      preLoaderRoute: typeof AgentDashboardIntroductionsRouteImport
      parentRoute: typeof AgentDashboardRoute
    }
    '/agent/dashboard/compliance': {
      id: '/agent/dashboard/compliance'
      path: '/compliance'
      fullPath: '/agent/dashboard/compliance'
      preLoaderRoute: typeof AgentDashboardComplianceRouteImport
      parentRoute: typeof AgentDashboardRoute
    }
    '/api/ingest/static/$': {
      id: '/api/ingest/static/$'
      path: '/api/ingest/static/$'
      fullPath: '/api/ingest/static/$'
      preLoaderRoute: typeof ApiIngestStaticSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AgentDashboardRouteChildren {
  AgentDashboardComplianceRoute: typeof AgentDashboardComplianceRoute
  AgentDashboardIntroductionsRoute: typeof AgentDashboardIntroductionsRoute
  AgentDashboardPeacePactRoute: typeof AgentDashboardPeacePactRoute
  AgentDashboardProfileRoute: typeof AgentDashboardProfileRoute
  AgentDashboardSubscribeRoute: typeof AgentDashboardSubscribeRoute
  AgentDashboardValuePropositionRoute: typeof AgentDashboardValuePropositionRoute
  AgentDashboardIndexRoute: typeof AgentDashboardIndexRoute
}

const AgentDashboardRouteChildren: AgentDashboardRouteChildren = {
  AgentDashboardComplianceRoute: AgentDashboardComplianceRoute,
  AgentDashboardIntroductionsRoute: AgentDashboardIntroductionsRoute,
  AgentDashboardPeacePactRoute: AgentDashboardPeacePactRoute,
  AgentDashboardProfileRoute: AgentDashboardProfileRoute,
  AgentDashboardSubscribeRoute: AgentDashboardSubscribeRoute,
  AgentDashboardValuePropositionRoute: AgentDashboardValuePropositionRoute,
  AgentDashboardIndexRoute: AgentDashboardIndexRoute,
}

const AgentDashboardRouteWithChildren = AgentDashboardRoute._addFileChildren(
  AgentDashboardRouteChildren,
)

interface ConsumerDashboardRouteChildren {
  ConsumerDashboardIntroductionsRoute: typeof ConsumerDashboardIntroductionsRoute
  ConsumerDashboardMatchesRoute: typeof ConsumerDashboardMatchesRoute
  ConsumerDashboardPracticeNegotiatingRoute: typeof ConsumerDashboardPracticeNegotiatingRoute
  ConsumerDashboardSearchPreferencesRoute: typeof ConsumerDashboardSearchPreferencesRoute
  ConsumerDashboardIndexRoute: typeof ConsumerDashboardIndexRoute
}

const ConsumerDashboardRouteChildren: ConsumerDashboardRouteChildren = {
  ConsumerDashboardIntroductionsRoute: ConsumerDashboardIntroductionsRoute,
  ConsumerDashboardMatchesRoute: ConsumerDashboardMatchesRoute,
  ConsumerDashboardPracticeNegotiatingRoute:
    ConsumerDashboardPracticeNegotiatingRoute,
  ConsumerDashboardSearchPreferencesRoute:
    ConsumerDashboardSearchPreferencesRoute,
  ConsumerDashboardIndexRoute: ConsumerDashboardIndexRoute,
}

const ConsumerDashboardRouteWithChildren =
  ConsumerDashboardRoute._addFileChildren(ConsumerDashboardRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BetaRoute: BetaRoute,
  LoginRoute: LoginRoute,
  AgentDashboardRoute: AgentDashboardRouteWithChildren,
  ApiAgentMatchesRoute: ApiAgentMatchesRoute,
  ConsumerDashboardRoute: ConsumerDashboardRouteWithChildren,
  AgentIndexRoute: AgentIndexRoute,
  ConsumerIndexRoute: ConsumerIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiBetaAuthRoute: ApiBetaAuthRoute,
  ApiIngestSplatRoute: ApiIngestSplatRoute,
  AgentSignupIndexRoute: AgentSignupIndexRoute,
  ConsumerSignupIndexRoute: ConsumerSignupIndexRoute,
  ApiIngestStaticSplatRoute: ApiIngestStaticSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
