/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as MatchesRouteImport } from './routes/matches'
import { Route as LoginRouteImport } from './routes/login'
import { Route as BetaRouteImport } from './routes/beta'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BuyerIndexRouteImport } from './routes/buyer/index'
import { Route as AgentIndexRouteImport } from './routes/agent/index'
import { Route as AccountIndexRouteImport } from './routes/account/index'
import { Route as BuyerPrioritiesRouteImport } from './routes/buyer/priorities'
import { Route as BuyerPreviewRouteImport } from './routes/buyer/preview'
import { Route as BuyerPaymentRouteImport } from './routes/buyer/payment'
import { Route as BuyerIntakeRouteImport } from './routes/buyer/intake'
import { Route as BuyerCompleteProfileRouteImport } from './routes/buyer/complete-profile'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiAgentMatchesRouteImport } from './routes/api/agent-matches'
import { Route as AgentSubscribeRouteImport } from './routes/agent/subscribe'
import { Route as AgentQuizRouteImport } from './routes/agent/quiz'
import { Route as AgentProfileRouteImport } from './routes/agent/profile'
import { Route as AgentPrioritiesRouteImport } from './routes/agent/priorities'
import { Route as AgentPeacePactRouteImport } from './routes/agent/peace-pact'
import { Route as AgentDeepDiveRouteImport } from './routes/agent/deep-dive'
import { Route as AgentComplianceRouteImport } from './routes/agent/compliance'
import { Route as AgentChatRouteImport } from './routes/agent/chat'
import { Route as AccountSearchPreferencesRouteImport } from './routes/account/search-preferences'
import { Route as AccountPracticeNegotiatingRouteImport } from './routes/account/practice-negotiating'
import { Route as AccountIntroductionsRouteImport } from './routes/account/introductions'
import { Route as ApiIngestSplatRouteImport } from './routes/api/ingest/$'
import { Route as ApiBetaAuthRouteImport } from './routes/api/beta/auth'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiIngestStaticSplatRouteImport } from './routes/api/ingest/static/$'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesRoute = MatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const BetaRoute = BetaRouteImport.update({
  id: '/beta',
  path: '/beta',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyerIndexRoute = BuyerIndexRouteImport.update({
  id: '/buyer/',
  path: '/buyer/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentIndexRoute = AgentIndexRouteImport.update({
  id: '/agent/',
  path: '/agent/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountRoute,
} as any)
const BuyerPrioritiesRoute = BuyerPrioritiesRouteImport.update({
  id: '/buyer/priorities',
  path: '/buyer/priorities',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyerPreviewRoute = BuyerPreviewRouteImport.update({
  id: '/buyer/preview',
  path: '/buyer/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyerPaymentRoute = BuyerPaymentRouteImport.update({
  id: '/buyer/payment',
  path: '/buyer/payment',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyerIntakeRoute = BuyerIntakeRouteImport.update({
  id: '/buyer/intake',
  path: '/buyer/intake',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyerCompleteProfileRoute = BuyerCompleteProfileRouteImport.update({
  id: '/buyer/complete-profile',
  path: '/buyer/complete-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentMatchesRoute = ApiAgentMatchesRouteImport.update({
  id: '/api/agent-matches',
  path: '/api/agent-matches',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentSubscribeRoute = AgentSubscribeRouteImport.update({
  id: '/agent/subscribe',
  path: '/agent/subscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentQuizRoute = AgentQuizRouteImport.update({
  id: '/agent/quiz',
  path: '/agent/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentProfileRoute = AgentProfileRouteImport.update({
  id: '/agent/profile',
  path: '/agent/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentPrioritiesRoute = AgentPrioritiesRouteImport.update({
  id: '/agent/priorities',
  path: '/agent/priorities',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentPeacePactRoute = AgentPeacePactRouteImport.update({
  id: '/agent/peace-pact',
  path: '/agent/peace-pact',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentDeepDiveRoute = AgentDeepDiveRouteImport.update({
  id: '/agent/deep-dive',
  path: '/agent/deep-dive',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentComplianceRoute = AgentComplianceRouteImport.update({
  id: '/agent/compliance',
  path: '/agent/compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentChatRoute = AgentChatRouteImport.update({
  id: '/agent/chat',
  path: '/agent/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountSearchPreferencesRoute =
  AccountSearchPreferencesRouteImport.update({
    id: '/search-preferences',
    path: '/search-preferences',
    getParentRoute: () => AccountRoute,
  } as any)
const AccountPracticeNegotiatingRoute =
  AccountPracticeNegotiatingRouteImport.update({
    id: '/practice-negotiating',
    path: '/practice-negotiating',
    getParentRoute: () => AccountRoute,
  } as any)
const AccountIntroductionsRoute = AccountIntroductionsRouteImport.update({
  id: '/introductions',
  path: '/introductions',
  getParentRoute: () => AccountRoute,
} as any)
const ApiIngestSplatRoute = ApiIngestSplatRouteImport.update({
  id: '/api/ingest/$',
  path: '/api/ingest/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBetaAuthRoute = ApiBetaAuthRouteImport.update({
  id: '/api/beta/auth',
  path: '/api/beta/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIngestStaticSplatRoute = ApiIngestStaticSplatRouteImport.update({
  id: '/api/ingest/static/$',
  path: '/api/ingest/static/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRouteWithChildren
  '/beta': typeof BetaRoute
  '/login': typeof LoginRoute
  '/matches': typeof MatchesRoute
  '/signup': typeof SignupRoute
  '/account/introductions': typeof AccountIntroductionsRoute
  '/account/practice-negotiating': typeof AccountPracticeNegotiatingRoute
  '/account/search-preferences': typeof AccountSearchPreferencesRoute
  '/agent/chat': typeof AgentChatRoute
  '/agent/compliance': typeof AgentComplianceRoute
  '/agent/deep-dive': typeof AgentDeepDiveRoute
  '/agent/peace-pact': typeof AgentPeacePactRoute
  '/agent/priorities': typeof AgentPrioritiesRoute
  '/agent/profile': typeof AgentProfileRoute
  '/agent/quiz': typeof AgentQuizRoute
  '/agent/subscribe': typeof AgentSubscribeRoute
  '/api/agent-matches': typeof ApiAgentMatchesRoute
  '/api/health': typeof ApiHealthRoute
  '/buyer/complete-profile': typeof BuyerCompleteProfileRoute
  '/buyer/intake': typeof BuyerIntakeRoute
  '/buyer/payment': typeof BuyerPaymentRoute
  '/buyer/preview': typeof BuyerPreviewRoute
  '/buyer/priorities': typeof BuyerPrioritiesRoute
  '/account/': typeof AccountIndexRoute
  '/agent/': typeof AgentIndexRoute
  '/buyer/': typeof BuyerIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/beta/auth': typeof ApiBetaAuthRoute
  '/api/ingest/$': typeof ApiIngestSplatRoute
  '/api/ingest/static/$': typeof ApiIngestStaticSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/beta': typeof BetaRoute
  '/login': typeof LoginRoute
  '/matches': typeof MatchesRoute
  '/signup': typeof SignupRoute
  '/account/introductions': typeof AccountIntroductionsRoute
  '/account/practice-negotiating': typeof AccountPracticeNegotiatingRoute
  '/account/search-preferences': typeof AccountSearchPreferencesRoute
  '/agent/chat': typeof AgentChatRoute
  '/agent/compliance': typeof AgentComplianceRoute
  '/agent/deep-dive': typeof AgentDeepDiveRoute
  '/agent/peace-pact': typeof AgentPeacePactRoute
  '/agent/priorities': typeof AgentPrioritiesRoute
  '/agent/profile': typeof AgentProfileRoute
  '/agent/quiz': typeof AgentQuizRoute
  '/agent/subscribe': typeof AgentSubscribeRoute
  '/api/agent-matches': typeof ApiAgentMatchesRoute
  '/api/health': typeof ApiHealthRoute
  '/buyer/complete-profile': typeof BuyerCompleteProfileRoute
  '/buyer/intake': typeof BuyerIntakeRoute
  '/buyer/payment': typeof BuyerPaymentRoute
  '/buyer/preview': typeof BuyerPreviewRoute
  '/buyer/priorities': typeof BuyerPrioritiesRoute
  '/account': typeof AccountIndexRoute
  '/agent': typeof AgentIndexRoute
  '/buyer': typeof BuyerIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/beta/auth': typeof ApiBetaAuthRoute
  '/api/ingest/$': typeof ApiIngestSplatRoute
  '/api/ingest/static/$': typeof ApiIngestStaticSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRouteWithChildren
  '/beta': typeof BetaRoute
  '/login': typeof LoginRoute
  '/matches': typeof MatchesRoute
  '/signup': typeof SignupRoute
  '/account/introductions': typeof AccountIntroductionsRoute
  '/account/practice-negotiating': typeof AccountPracticeNegotiatingRoute
  '/account/search-preferences': typeof AccountSearchPreferencesRoute
  '/agent/chat': typeof AgentChatRoute
  '/agent/compliance': typeof AgentComplianceRoute
  '/agent/deep-dive': typeof AgentDeepDiveRoute
  '/agent/peace-pact': typeof AgentPeacePactRoute
  '/agent/priorities': typeof AgentPrioritiesRoute
  '/agent/profile': typeof AgentProfileRoute
  '/agent/quiz': typeof AgentQuizRoute
  '/agent/subscribe': typeof AgentSubscribeRoute
  '/api/agent-matches': typeof ApiAgentMatchesRoute
  '/api/health': typeof ApiHealthRoute
  '/buyer/complete-profile': typeof BuyerCompleteProfileRoute
  '/buyer/intake': typeof BuyerIntakeRoute
  '/buyer/payment': typeof BuyerPaymentRoute
  '/buyer/preview': typeof BuyerPreviewRoute
  '/buyer/priorities': typeof BuyerPrioritiesRoute
  '/account/': typeof AccountIndexRoute
  '/agent/': typeof AgentIndexRoute
  '/buyer/': typeof BuyerIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/beta/auth': typeof ApiBetaAuthRoute
  '/api/ingest/$': typeof ApiIngestSplatRoute
  '/api/ingest/static/$': typeof ApiIngestStaticSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/beta'
    | '/login'
    | '/matches'
    | '/signup'
    | '/account/introductions'
    | '/account/practice-negotiating'
    | '/account/search-preferences'
    | '/agent/chat'
    | '/agent/compliance'
    | '/agent/deep-dive'
    | '/agent/peace-pact'
    | '/agent/priorities'
    | '/agent/profile'
    | '/agent/quiz'
    | '/agent/subscribe'
    | '/api/agent-matches'
    | '/api/health'
    | '/buyer/complete-profile'
    | '/buyer/intake'
    | '/buyer/payment'
    | '/buyer/preview'
    | '/buyer/priorities'
    | '/account/'
    | '/agent/'
    | '/buyer/'
    | '/api/auth/$'
    | '/api/beta/auth'
    | '/api/ingest/$'
    | '/api/ingest/static/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/beta'
    | '/login'
    | '/matches'
    | '/signup'
    | '/account/introductions'
    | '/account/practice-negotiating'
    | '/account/search-preferences'
    | '/agent/chat'
    | '/agent/compliance'
    | '/agent/deep-dive'
    | '/agent/peace-pact'
    | '/agent/priorities'
    | '/agent/profile'
    | '/agent/quiz'
    | '/agent/subscribe'
    | '/api/agent-matches'
    | '/api/health'
    | '/buyer/complete-profile'
    | '/buyer/intake'
    | '/buyer/payment'
    | '/buyer/preview'
    | '/buyer/priorities'
    | '/account'
    | '/agent'
    | '/buyer'
    | '/api/auth/$'
    | '/api/beta/auth'
    | '/api/ingest/$'
    | '/api/ingest/static/$'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/beta'
    | '/login'
    | '/matches'
    | '/signup'
    | '/account/introductions'
    | '/account/practice-negotiating'
    | '/account/search-preferences'
    | '/agent/chat'
    | '/agent/compliance'
    | '/agent/deep-dive'
    | '/agent/peace-pact'
    | '/agent/priorities'
    | '/agent/profile'
    | '/agent/quiz'
    | '/agent/subscribe'
    | '/api/agent-matches'
    | '/api/health'
    | '/buyer/complete-profile'
    | '/buyer/intake'
    | '/buyer/payment'
    | '/buyer/preview'
    | '/buyer/priorities'
    | '/account/'
    | '/agent/'
    | '/buyer/'
    | '/api/auth/$'
    | '/api/beta/auth'
    | '/api/ingest/$'
    | '/api/ingest/static/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRouteWithChildren
  BetaRoute: typeof BetaRoute
  LoginRoute: typeof LoginRoute
  MatchesRoute: typeof MatchesRoute
  SignupRoute: typeof SignupRoute
  AgentChatRoute: typeof AgentChatRoute
  AgentComplianceRoute: typeof AgentComplianceRoute
  AgentDeepDiveRoute: typeof AgentDeepDiveRoute
  AgentPeacePactRoute: typeof AgentPeacePactRoute
  AgentPrioritiesRoute: typeof AgentPrioritiesRoute
  AgentProfileRoute: typeof AgentProfileRoute
  AgentQuizRoute: typeof AgentQuizRoute
  AgentSubscribeRoute: typeof AgentSubscribeRoute
  ApiAgentMatchesRoute: typeof ApiAgentMatchesRoute
  ApiHealthRoute: typeof ApiHealthRoute
  BuyerCompleteProfileRoute: typeof BuyerCompleteProfileRoute
  BuyerIntakeRoute: typeof BuyerIntakeRoute
  BuyerPaymentRoute: typeof BuyerPaymentRoute
  BuyerPreviewRoute: typeof BuyerPreviewRoute
  BuyerPrioritiesRoute: typeof BuyerPrioritiesRoute
  AgentIndexRoute: typeof AgentIndexRoute
  BuyerIndexRoute: typeof BuyerIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiBetaAuthRoute: typeof ApiBetaAuthRoute
  ApiIngestSplatRoute: typeof ApiIngestSplatRoute
  ApiIngestStaticSplatRoute: typeof ApiIngestStaticSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches': {
      id: '/matches'
      path: '/matches'
      fullPath: '/matches'
      preLoaderRoute: typeof MatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beta': {
      id: '/beta'
      path: '/beta'
      fullPath: '/beta'
      preLoaderRoute: typeof BetaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buyer/': {
      id: '/buyer/'
      path: '/buyer'
      fullPath: '/buyer/'
      preLoaderRoute: typeof BuyerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/': {
      id: '/agent/'
      path: '/agent'
      fullPath: '/agent/'
      preLoaderRoute: typeof AgentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof AccountRoute
    }
    '/buyer/priorities': {
      id: '/buyer/priorities'
      path: '/buyer/priorities'
      fullPath: '/buyer/priorities'
      preLoaderRoute: typeof BuyerPrioritiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buyer/preview': {
      id: '/buyer/preview'
      path: '/buyer/preview'
      fullPath: '/buyer/preview'
      preLoaderRoute: typeof BuyerPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buyer/payment': {
      id: '/buyer/payment'
      path: '/buyer/payment'
      fullPath: '/buyer/payment'
      preLoaderRoute: typeof BuyerPaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buyer/intake': {
      id: '/buyer/intake'
      path: '/buyer/intake'
      fullPath: '/buyer/intake'
      preLoaderRoute: typeof BuyerIntakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buyer/complete-profile': {
      id: '/buyer/complete-profile'
      path: '/buyer/complete-profile'
      fullPath: '/buyer/complete-profile'
      preLoaderRoute: typeof BuyerCompleteProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent-matches': {
      id: '/api/agent-matches'
      path: '/api/agent-matches'
      fullPath: '/api/agent-matches'
      preLoaderRoute: typeof ApiAgentMatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/subscribe': {
      id: '/agent/subscribe'
      path: '/agent/subscribe'
      fullPath: '/agent/subscribe'
      preLoaderRoute: typeof AgentSubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/quiz': {
      id: '/agent/quiz'
      path: '/agent/quiz'
      fullPath: '/agent/quiz'
      preLoaderRoute: typeof AgentQuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/profile': {
      id: '/agent/profile'
      path: '/agent/profile'
      fullPath: '/agent/profile'
      preLoaderRoute: typeof AgentProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/priorities': {
      id: '/agent/priorities'
      path: '/agent/priorities'
      fullPath: '/agent/priorities'
      preLoaderRoute: typeof AgentPrioritiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/peace-pact': {
      id: '/agent/peace-pact'
      path: '/agent/peace-pact'
      fullPath: '/agent/peace-pact'
      preLoaderRoute: typeof AgentPeacePactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/deep-dive': {
      id: '/agent/deep-dive'
      path: '/agent/deep-dive'
      fullPath: '/agent/deep-dive'
      preLoaderRoute: typeof AgentDeepDiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/compliance': {
      id: '/agent/compliance'
      path: '/agent/compliance'
      fullPath: '/agent/compliance'
      preLoaderRoute: typeof AgentComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/chat': {
      id: '/agent/chat'
      path: '/agent/chat'
      fullPath: '/agent/chat'
      preLoaderRoute: typeof AgentChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/search-preferences': {
      id: '/account/search-preferences'
      path: '/search-preferences'
      fullPath: '/account/search-preferences'
      preLoaderRoute: typeof AccountSearchPreferencesRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/practice-negotiating': {
      id: '/account/practice-negotiating'
      path: '/practice-negotiating'
      fullPath: '/account/practice-negotiating'
      preLoaderRoute: typeof AccountPracticeNegotiatingRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/introductions': {
      id: '/account/introductions'
      path: '/introductions'
      fullPath: '/account/introductions'
      preLoaderRoute: typeof AccountIntroductionsRouteImport
      parentRoute: typeof AccountRoute
    }
    '/api/ingest/$': {
      id: '/api/ingest/$'
      path: '/api/ingest/$'
      fullPath: '/api/ingest/$'
      preLoaderRoute: typeof ApiIngestSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/beta/auth': {
      id: '/api/beta/auth'
      path: '/api/beta/auth'
      fullPath: '/api/beta/auth'
      preLoaderRoute: typeof ApiBetaAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ingest/static/$': {
      id: '/api/ingest/static/$'
      path: '/api/ingest/static/$'
      fullPath: '/api/ingest/static/$'
      preLoaderRoute: typeof ApiIngestStaticSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AccountRouteChildren {
  AccountIntroductionsRoute: typeof AccountIntroductionsRoute
  AccountPracticeNegotiatingRoute: typeof AccountPracticeNegotiatingRoute
  AccountSearchPreferencesRoute: typeof AccountSearchPreferencesRoute
  AccountIndexRoute: typeof AccountIndexRoute
}

const AccountRouteChildren: AccountRouteChildren = {
  AccountIntroductionsRoute: AccountIntroductionsRoute,
  AccountPracticeNegotiatingRoute: AccountPracticeNegotiatingRoute,
  AccountSearchPreferencesRoute: AccountSearchPreferencesRoute,
  AccountIndexRoute: AccountIndexRoute,
}

const AccountRouteWithChildren =
  AccountRoute._addFileChildren(AccountRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRouteWithChildren,
  BetaRoute: BetaRoute,
  LoginRoute: LoginRoute,
  MatchesRoute: MatchesRoute,
  SignupRoute: SignupRoute,
  AgentChatRoute: AgentChatRoute,
  AgentComplianceRoute: AgentComplianceRoute,
  AgentDeepDiveRoute: AgentDeepDiveRoute,
  AgentPeacePactRoute: AgentPeacePactRoute,
  AgentPrioritiesRoute: AgentPrioritiesRoute,
  AgentProfileRoute: AgentProfileRoute,
  AgentQuizRoute: AgentQuizRoute,
  AgentSubscribeRoute: AgentSubscribeRoute,
  ApiAgentMatchesRoute: ApiAgentMatchesRoute,
  ApiHealthRoute: ApiHealthRoute,
  BuyerCompleteProfileRoute: BuyerCompleteProfileRoute,
  BuyerIntakeRoute: BuyerIntakeRoute,
  BuyerPaymentRoute: BuyerPaymentRoute,
  BuyerPreviewRoute: BuyerPreviewRoute,
  BuyerPrioritiesRoute: BuyerPrioritiesRoute,
  AgentIndexRoute: AgentIndexRoute,
  BuyerIndexRoute: BuyerIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiBetaAuthRoute: ApiBetaAuthRoute,
  ApiIngestSplatRoute: ApiIngestSplatRoute,
  ApiIngestStaticSplatRoute: ApiIngestStaticSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
